
[tool.towncrier]
package = "lsst.ts.config_mtcalsys"
package_dir = "python"
filename = "doc/version-history.rst"
directory = "doc/news"
filename_format = "{name}.{type}.rst|{name}.{type}.md"
title_format = "{version} ({project_date})"
issue_format = "`{issue} <https://rubinobs.atlassian.net/browse/{issue}>`_"

[[tool.towncrier.section]]
name = "Package Level"
path = ""

[[tool.towncrier.section]]
name = "Interface Changes"
path = "interface_changes"

[[tool.towncrier.type]]
directory = "feature"
name = "New Features"
showcontent = true

[[tool.towncrier.type]]
directory = "bugfix"
name = "Bug Fixes"
showcontent = true

[[tool.towncrier.type]]
directory = "perf"
name = "Performance Enhancement"
showcontent = true

[[tool.towncrier.type]]
directory = "doc"
name = "Documentation"
showcontent = true

[[tool.towncrier.type]]
directory = "removal"
name = "API Removal or Deprecation"
showcontent = true

[[tool.towncrier.type]]
directory = "misc"
name = "Other Changes and Additions"
showcontent = true

